import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faArrowRightFromBracket,
  faCalendarDays,
  faChevronLeft,
  faCircleInfo,
  faClipboard,
  faEnvelope,
  faFaceSmile,
  faKey,
  faMagnifyingGlass,
  faMessage,
  faMinus,
  faPaperclip,
  faPencil,
  faPlus,
  faSackDollar,
  faSpinner,
  faTrash,
  faUser,
  faUserGroup,
} from "@fortawesome/free-solid-svg-icons";
import { faGem } from "@fortawesome/free-regular-svg-icons";

library.add(
  faUser,
  faMagnifyingGlass,
  faSpinner,
  faPlus,
  faMinus,
  faClipboard,
  faCalendarDays,
  faSackDollar,
  faChevronLeft,
  faTrash,
  faPencil,
  faKey,
  faGem,
  faEnvelope,
  faPaperclip,
  faFaceSmile,
  faArrowRight,
  faCircleInfo,
  faUserGroup,
  faArrowRightFromBracket,
  faMessage
);
